### ISSUE TITLE
tutorial or any kind of help on how to set up correctly? pls

### ISSUE THREAD

**Issue by LilUzziii** [Sacchan-VRC/SaccFlightAndVehicles#1]

**Comment by Sacchan-VRC** [comment]
There's a Readme.txt with a lot of information in(separate from readme.md), and I just uploaded the booth release version to github, in case you don't have an account there. You should use that version, as between-releases everything is going to be completely broken, because I don't update the prefab for every commit.

You can just place the prefab into your unity scene(SaccFlightAndVehicles.prefab), and as long as you have VRChat SDK3, and UdonSharp installed it should work IN VRChat right away. To test inside the editor you need to set up the inputs configuration of your unity project to include the names of the ones used in VRChat. There are more details in the readme, and an example image.

If you want to make a custom plane it's basically a matter of replacing the PlaneBody object. The hard part is setting up the model in such a way that the control surfaces rotate on the correct axis. You can look at the prefab to see how I did it, it's using empty objects to set an axis, and parenting the control surfaces to them. You must also check each animation to make sure no references get messed up when customizing things.

There is a discord link in the readme if you'd like more direct help.
